
CREATE view [dbo].[cartera_v] as
(
	select
	dt.*,
	concat(telefonosAGC,iif(telefonosAGC='','',','),dt.tels)as telefono
	from(
		select
		cl.idCliente,
		cl.idClienteT,
		cl.codigo,
		cl.nombre as cliente,
		cl.direccion,
		ae.actividad as actividadEconomica,
		dbo.fStuff((SELECT top(5) ',' + telefono FROM telefonosCliente where idCliente = cl.idCliente order by idTelefono desc FOR XML PATH ('')))as telefonosAGC,
		cl.imgCasa,
		cl.imgNegocio,
		cl.pendienteCasa,
		cl.pendienteNegocio,
		cl.telefono as tels,
		cl.latitud,
		cl.longitud,
		cl.latitudNegocio,
		cl.longitudNegocio,
		ca.idGestor,
		cr.idCredito,
		cr.idCreditoT,
		cr.referencia,
		cr.idAgencia,
		cr.pagoParaEstarAlDia,
		cr.valorCuota,
		cr.fechaProximaCuota,
		cr.diasCapitalMora,
		cr.gestionesRealizadas,
		cr.ultimoPago,
		cr.fechaOtorgamiento,
		cr.montoOtorgado,
		cr.deudaTotal,
		cr.gestionado,
		cr.capitalMora,
		cr.capitalTotalAdeudado,
		cr.montoReserva,
		cr.saldoCapitalVigente,
		cr.saldoCapitalVencido,
		cr.pagoParaTramo30,
		cr.pagoParaTramo60,
		cr.pagoParaTramo90,
		cr.ultimaFechaPago,
		cr.fechaVencimiento,
		cr.fechaCancelacion,
		DATEDIFF(MONTH,cr.fechaOtorgamiento,cr.fechaVencimiento)as plazo,
		cr.diasRestantesPlazo,
		cr.porVencer,
		cr.cuotaVenceHoy,
		cr.idEstado,
		cr.idLineaCredito,
		cr.tasaInteresNominal,
		cr.montoProximaCuota,
		lc.destino,
		cr.frecuencia,
		cr.cantidadCuotas,
		cr.prioridad creditoPrioridad,
		coalesce((select valor from prioridades where idPrioridad = cr.idPrioridad),0)as prioridad,
		coalesce(cr.prioridadAgencia,0)as prioridadAgencia,
		cr.diasPrioridad,
		cr.diasPrioridadAgencia,
		cr.promesas,
		cr.diasPromesa,
		cr.desembolso,
		cr.diasDesembolso,
		cr.desertado,
		cr.diasDesertado,
		iif(cr.diasDesertado > 0 ,(DATEADD(day,-cr.diasDesertado,getDate())),null)as fechaDesertado,
		coalesce(cr.porDesertar,0)as porDesertar,
		cr.diasPorDesertar,
		iif(cr.diasPorDesertar > 0 ,(DATEADD(day,-cr.diasPorDesertar,getDate())),null)as fechaDesercion,
		cr.seguimiento,
		cr.etapaSeguimiento,
		cr.renovacion,
		cr.calificacionCliente,
		cr.notaCliente,
		coalesce(lc.lineaCredito,'--')as lineaCredito,
		cr.DUG,
		cr.UG,
		cr.enMora,
		cr.atrasoMaximo,
		cr.atrasoPromedio,
		cr.cobroPreventivo,
		cr.titular,
		cr.d1,
		cr.vencimiento,
		cr.f1,
		ol.idOrganizacion,
		coalesce(ol.nombre,'Independiente')as organizacionLocal,
		ga.idGrupoAdesco,
		coalesce(ga.nombre,'Independiente') as grupo,
		iif(cr.idEstado = dbo.fEstadoCredito('S'),1,0) as saneado,
		cr.idProspecto,
		cr.infoE,
		cr.emergentes,
		cr.table_ext,
		cr.diasUltimoSeguimiento
		from creditosAsignados ca
		inner join creditos cr on cr.idCredito = ca.idCredito
		left join lineasCredito lc on lc.idLineaCredito = cr.idLineaCredito
		inner join clientes cl on cl.idCliente = cr.idCliente
		left join gruposAdesco ga on ga.idGrupoAdesco = cr.idGrupo
		left join organizacionesLocales ol on ol.idOrganizacion = ga.idOrganizacion
		left join actividadesEconomicas ae on ae.idActividadE=cl.idActividadE
		where cr.idEstado !=2 and ca.asignado != 0
	) as dt
)
